"""add code_name for chatbot

Revision ID: 444f8bfc1c35
Revises: f56087dfa386
Create Date: 2025-02-26 09:50:50.614903

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "444f8bfc1c35"
down_revision: Union[str, None] = "f56087dfa386"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chatbots",
        sa.Column("code_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chatbots", "code_name")
    # ### end Alembic commands ###
