"""update ondelete

Revision ID: a6f8a49f055d
Revises: e2778c92995d
Create Date: 2025-02-27 09:22:22.317972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a6f8a49f055d'
down_revision: Union[str, None] = 'e2778c92995d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_user_uid_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_uid'], ['uid'], ondelete='CASCADE')
    op.drop_constraint('messages_conversation_uid_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_conversation_uid_fkey', 'messages', 'conversations', ['conversation_uid'], ['uid'])
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_user_uid_fkey', 'conversations', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###
