"""fix atributes column chatbots

Revision ID: e2778c92995d
Revises: 444f8bfc1c35
Create Date: 2025-02-26 10:09:37.438070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e2778c92995d'
down_revision: Union[str, None] = '444f8bfc1c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbots', 'code_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbots', 'code_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
