"""update messages column

Revision ID: faa362f98ba8
Revises: a6f8a49f055d
Create Date: 2025-02-27 09:55:08.263834

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "faa362f98ba8"
down_revision: Union[str, None] = "a6f8a49f055d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversations", "user_uid", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "messages", "conversation_uid", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages", "conversation_uid", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column("conversations", "user_uid", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
